// ── data.js ───────────────────────────────────────────────────────────────────

const CHARACTERS_DATA = [
  {
    id:'ryo', name:'Ryo', type:'Femboy', rarity:3,
    emoji:'🌸', color:'#FF9ECD',
    grad:'linear-gradient(135deg,#FF9ECD 0%,#FFD6EE 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=Ryo&backgroundColor=ffc0cb&skinColor=f2d3b1',
    stats:{ charisma:8, strength:5, intelligence:7, social:7 },
    workBonus:0.10,
    description:'Soft-spoken barista who somehow makes every drink perfect.',
    quote:'"Does this look okay? …not that I care what you think."',
    reactions:{
      flower:'*blushes* W-why would you give me this…',
      meal:'You actually cooked? Let me try— …it\'s good.',
      boba:'I like the one with taro. Don\'t ask me why.',
      movie:'…you picked a horror film on purpose, didn\'t you.',
      games:'I\'m going easy on you. Don\'t flatter yourself.',
      letter:'I read it three times. For research purposes.',
      gift:'You didn\'t have to… but I\'m keeping it.',
      walk:'The night air is nice. Don\'t ruin it.',
    },
  },
  {
    id:'kai', name:'Kai', type:'Tomboy', rarity:2,
    emoji:'⚡', color:'#60A5FA',
    grad:'linear-gradient(135deg,#60A5FA 0%,#BAE6FD 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=KaiAthletic&backgroundColor=bfdbfe&skinColor=f2d3b1',
    stats:{ charisma:5, strength:9, intelligence:6, social:7 },
    workBonus:0.15,
    description:'First at the gym, last to admit feelings. Fiercely loyal.',
    quote:'"I\'m not looking for a fight. …but I\'ll win if it comes to one."',
    reactions:{
      flower:'Flowers? Seriously? …fine, whatever. It\'s pretty I guess.',
      meal:'Bro are you trying to out-cook me? Challenge accepted.',
      boba:'I wanted matcha. But this works.',
      movie:'Action movies only. No exceptions.',
      games:'Okay but I\'m not going easy on you.',
      letter:'You wrote this yourself? Huh. That\'s… cool.',
      gift:'You didn\'t need to spend that much—',
      walk:'Race you to that streetlight.',
    },
  },
  {
    id:'nova', name:'Nova', type:'Baddie', rarity:4,
    emoji:'💅', color:'#F59E0B',
    grad:'linear-gradient(135deg,#F59E0B 0%,#FDE68A 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=NovaBaddie&backgroundColor=fde68a&skinColor=d08b5b',
    stats:{ charisma:9, strength:7, intelligence:8, social:10 },
    workBonus:0.20,
    description:'Main character energy. Walks into a room and immediately owns it.',
    quote:'"Try to keep up, darling."',
    reactions:{
      flower:'Cute. Though I prefer something more… extravagant.',
      meal:'You cooked? For me? Okay, I\'m impressed. A little.',
      boba:'Make it oat milk. And get me a cookie.',
      movie:'We\'re watching a rom-com and you\'re going to love it.',
      games:'I let you win last time. This time? No mercy.',
      letter:'You really put effort into this. Adorable.',
      gift:'Finally, someone with taste.',
      walk:'Keep up. My heels are faster than your sneakers.',
    },
  },
  {
    id:'miku', name:'Miku', type:'Kuudere', rarity:2,
    emoji:'❄️', color:'#7DD3FC',
    grad:'linear-gradient(135deg,#7DD3FC 0%,#E0F2FE 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=MikuKuudere&backgroundColor=e0f2fe&skinColor=f2d3b1',
    stats:{ charisma:5, strength:6, intelligence:10, social:4 },
    workBonus:0.20,
    description:'Analytical, quiet, brilliant. Warms up eventually.',
    quote:'"I calculated a 73% chance you\'d say something predictable."',
    reactions:{
      flower:'Flowers have a 7-day average lifespan. Inefficient.',
      meal:'Nutritional value is acceptable. …it tastes fine.',
      boba:'The sugar content is excessive. I\'ll finish it.',
      movie:'I already know the plot twist. Predictable writing.',
      games:'I have a 94.3% win rate. Proceed at your own risk.',
      letter:'Your handwriting is inconsistent. The content was… adequate.',
      gift:'This was unnecessary. I will use it regardless.',
      walk:'Night air reduces cortisol by 18%. Logical choice.',
    },
  },
  {
    id:'yuki', name:'Yuki', type:'Gyaru', rarity:3,
    emoji:'🌟', color:'#FBBF24',
    grad:'linear-gradient(135deg,#FBBF24 0%,#FEF3C7 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=YukiGyaru&backgroundColor=fef3c7&skinColor=d08b5b',
    stats:{ charisma:8, strength:6, intelligence:6, social:9 },
    workBonus:0.10,
    description:'Loud, dramatic, and somehow the most genuine person in the room.',
    quote:'"OMG wait, you actually think I\'m annoying? That\'s hilarious."',
    reactions:{
      flower:'OMGGGG THEY\'RE SO PRETTY I\'M GOING TO CRY—',
      meal:'Wait wait wait you MADE THIS?? Bestie you can cook??',
      boba:'Okay the line was 30 minutes but SO worth it!',
      movie:'I already watched this 4 times but let\'s GO.',
      games:'I\'m literally so bad at this but screaming is half the fun.',
      letter:'I read it like 10 times?? You\'re so sweet I hate you.',
      gift:'I\'M OBSESSED. HOW DID YOU KNOW.',
      walk:'Okay the vibes tonight are IMMACULATE.',
    },
  },
  {
    id:'hana', name:'Hana', type:'Nerd', rarity:2,
    emoji:'📚', color:'#86EFAC',
    grad:'linear-gradient(135deg,#86EFAC 0%,#DCFCE7 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=HanaNerd&backgroundColor=dcfce7&skinColor=f2d3b1',
    stats:{ charisma:5, strength:4, intelligence:10, social:5 },
    workBonus:0.25,
    description:'Probably read 14 books this week. Lends you one. Quizzes you later.',
    quote:'"Actually, the historically accurate version is far more interesting."',
    reactions:{
      flower:'Did you know this species blooms biennially? Fascinating.',
      meal:'The Maillard reaction in this is excellent.',
      boba:'I brought a book. We can read in companionable silence.',
      movie:'The original novel was better, but the cinematography was adequate.',
      games:'I\'ve been studying optimal strategies. Let\'s begin.',
      letter:'Your sentence structure was surprisingly sophisticated.',
      gift:'This is literally on my wishlist. Did you check my notes?',
      walk:'The constellation visibility tonight is exceptional.',
    },
  },
  {
    id:'sora', name:'Sora', type:'Tsundere', rarity:5,
    emoji:'🌙', color:'#DDA0DD',
    grad:'linear-gradient(135deg,#DDA0DD 0%,#F3E8FF 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=SoraTsundere&backgroundColor=f3e8ff&skinColor=f2d3b1',
    stats:{ charisma:9, strength:8, intelligence:9, social:7 },
    workBonus:0.35,
    description:'Says she doesn\'t care. Made you lunch. Left before you woke up.',
    quote:'"I-it\'s not like I wanted to see you or anything…"',
    reactions:{
      flower:'I-it\'s not like flowers mean anything! I\'ll throw it away. …later.',
      meal:'It\'s decent. D-don\'t take that as a compliment.',
      boba:'I didn\'t want to come but someone had to make sure you didn\'t get lost.',
      movie:'I\'m not scared. I just moved closer for warmth. Obviously.',
      games:'I\'m letting you win. For your self-esteem.',
      letter:'I read it. Once. Maybe twice. It was fine.',
      gift:'You— this is— I didn\'t ask for this. I\'m keeping it.',
      walk:'Walk faster. And don\'t read into this.',
    },
  },
  {
    id:'ren', name:'Ren', type:'Dandere', rarity:3,
    emoji:'🍃', color:'#6EE7B7',
    grad:'linear-gradient(135deg,#6EE7B7 0%,#CCFBF1 100%)',
    img:'https://api.dicebear.com/7.x/adventurer/svg?seed=RenDandere&backgroundColor=ccfbf1&skinColor=f2d3b1',
    stats:{ charisma:7, strength:6, intelligence:8, social:6 },
    workBonus:0.15,
    description:'Quiet until they trust you. Then they never stop talking.',
    quote:'"…you actually want to hear about it? …okay."',
    reactions:{
      flower:'…thank you. I pressed the last one you gave me.',
      meal:'You remembered my favourite. …that means a lot.',
      boba:'I like sitting here with you. It\'s… comfortable.',
      movie:'…can we watch it again? I missed a part.',
      games:'I get nervous playing with people. But. Not with you.',
      letter:'I still have all your letters. In a box. Just so you know.',
      gift:'…I don\'t know what to say. This is really thoughtful.',
      walk:'I know a shortcut but I don\'t want to take it yet.',
    },
  },
];

const RARITY_WEIGHTS = { 2:40, 3:35, 4:20, 5:5 };

const RARITY_META = {
  2:{ name:'Rare',       color:'#60A5FA', stars:'⭐⭐'        },
  3:{ name:'Super Rare', color:'#7C3AED', stars:'⭐⭐⭐'      },
  4:{ name:'Epic',       color:'#F59E0B', stars:'⭐⭐⭐⭐'    },
  5:{ name:'Legendary',  color:'#FF2D78', stars:'⭐⭐⭐⭐⭐'  },
};

const JOBS_DATA = [
  { id:'barista', name:'Café Barista',    emoji:'☕', basePay:60,  duration:120, desc:'Craft drinks, deal with picky orders.'  },
  { id:'creator', name:'Content Creator', emoji:'📱', basePay:150, duration:300, desc:'Post, edit, collab, repeat.'           },
  { id:'model',   name:'Freelance Model', emoji:'📸', basePay:280, duration:600, desc:'Photoshoots, runway, brand deals.'      },
  { id:'dev',     name:'Software Dev',    emoji:'💻', basePay:450, duration:900, desc:'Code, debug, coffee, repeat.'          },
];

const INTERACTIONS_DATA = [
  { id:'flower', name:'Give Flower',  emoji:'🌸', cost:50,  affection:5,  msg:'gifted a flower'           },
  { id:'meal',   name:'Share Meal',   emoji:'🍱', cost:35,  affection:4,  msg:'shared a home-cooked meal'  },
  { id:'boba',   name:'Boba Date',    emoji:'🧋', cost:80,  affection:9,  msg:'went on a boba date'        },
  { id:'movie',  name:'Movie Night',  emoji:'🎬', cost:65,  affection:7,  msg:'watched a movie together'   },
  { id:'games',  name:'Play Games',   emoji:'🎮', cost:45,  affection:5,  msg:'played games together'      },
  { id:'letter', name:'Write Letter', emoji:'💌', cost:25,  affection:3,  msg:'wrote a heartfelt letter'   },
  { id:'gift',   name:'Give Gift',    emoji:'🎁', cost:120, affection:12, msg:'gave a special gift'        },
  { id:'walk',   name:'Night Walk',   emoji:'🌃', cost:90,  affection:10, msg:'took a night walk'          },
];

const AFFECTION_LEVELS = [
  { min:0,   max:19,  title:'Stranger',     color:'#6B7280' },
  { min:20,  max:39,  title:'Acquaintance', color:'#60A5FA' },
  { min:40,  max:59,  title:'Friend',       color:'#34D399' },
  { min:60,  max:79,  title:'Close',        color:'#A78BFA' },
  { min:80,  max:99,  title:'Beloved',      color:'#F472B6' },
  { min:100, max:149, title:'Soulmate',     color:'#FF2D78' },
  { min:150, max:999, title:'Eternal Bond', color:'#FFD700' },
];

// Shards needed per star upgrade
const SHARDS_PER_UPGRADE = 3;
const MAX_STAR_BONUS     = 2;
